# Generated by Django 2.1.3 on 2018-12-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techintapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='techintapp2.Person')),
            ],
            bases=('techintapp2.person',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('description', models.CharField(max_length=1000, verbose_name='Opis')),
                ('client', models.CharField(max_length=1000, verbose_name='Klient')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='techintapp2.Person')),
                ('specialisation', models.CharField(max_length=50, verbose_name='Specjalizacja')),
            ],
            bases=('techintapp2.person',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('description', models.CharField(max_length=1000, verbose_name='Opis')),
                ('time_elapsed', models.IntegerField(blank=True, default=None, null=True, verbose_name='Przepracowany czas')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.AddField(
            model_name='task',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techintapp2.Person', verbose_name='Wykonawca'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='techintapp2.Project', verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='developer',
            name='dev_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techintapp2.Supervisor', verbose_name='Przełożony'),
        ),
    ]
